###########################################################
#
# This role can be called anytime to repeat creds download
#

- name: Get the credentials ZIP file
  shell: rm -rfv "{{ euca_admin_zip }}" ;
         euca-get-credentials "{{ euca_admin_zip }}" -u "{{ user }}" -a "{{ account }}"
  tags:
  - euca_creds

- name: Creates the creds target directory
  shell: mkdir -p "{{ euca_admin_creds_path }}"
  tags:
  - euca_creds
  ignore_errors: yes

- name: Debug
  debug: msg="{{ euca_admin_zip }}"

- name: Unzip the credentials
  unarchive: copy=no src="{{ euca_admin_zip }}" dest="{{ euca_admin_creds_path }}" creates=yes
  tags:
  - euca_creds

- name: Check all services
  shell: source "{{ euca_admin_creds }}"; euca-describe-services
  tags:
  - euca_creds
  ignore_errors: yes

- name: Update eucarc with EC2_PRIVATE_KEY
  lineinfile: src="{{ euca_admin_creds_path }}"/eucarc
              dest="{{ euca_admin_creds_path }}"/eucarc
              insertafter='^export EC2_USER_ID' line="export EC2_PRIVATE_KEY=$EUCA_KEY_DIR/`ls $EUCA_KEY_DIR |  grep pem | grep euca2 | grep admin | grep pk`"
  tags:
  - euca_creds
  ignore_errors: yes

- name: Update eucarc with EC2_CERT
  lineinfile: src="{{ euca_admin_creds_path }}"/eucarc
              dest="{{ euca_admin_creds_path }}"/eucarc
              insertafter='^export EC2_USER_ID'
              line="export EC2_CERT=$EUCA_KEY_DIR/`ls $EUCA_KEY_DIR |  grep pem | grep euca2 | grep admin | grep cert`"
  tags:
  - euca_creds
  ignore_errors: yes
